### ISSUE TITLE
Remove alert noice

### ISSUE THREAD

**Issue by Quaticy** [totles/z4lab-hub#3]
Could you make a smx file or sp file where the alert sound goes away?

**Comment by 13ace37** [comment]
You could just clone it and remove https://github.com/z4lab/z4lab-hub/blob/master/addons/sourcemod/scripting/z4lab-hub.sp#L157 your self.

**Comment by Quaticy** [comment]
When i remove it, it still plays the sound

**Comment by 13ace37** [comment]
You need to compile it :)

**Comment by Quaticy** [comment]
How do i do that? Hehe

**Comment by 13ace37** [comment]
normally you would use the binary compiler. but for single filed plugins, you can use https://www.sourcemod.net/compiler.php

**Comment by Quaticy** [comment]
Thank you so much ❤️

**Comment by Quaticy** [comment]
I get this error Your plugin failed to compile! Read the errors below:
SourcePawn Compiler 1.10.0.6453
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

/home/groups/sourcemod/upload_tmp/phpbYqrqQ.sp(2) : fatal error 183: cannot read from file: "colorvariables"

Compilation aborted.
1 Error.

**Comment by Quaticy** [comment]
Could you compile this for me?

**Comment by Quaticy** [comment]
[z4lab-hub.zip](https://github.com/z4lab/z4lab-hub/files/4124378/z4lab-hub.zip)
