### ISSUE TITLE
Compiling the sp file not working

### ISSUE THREAD

**Issue by Quaticy** [totles/z4lab-hub#5]
Ok, so when i compile your sp file to remove the sound when typing !ws in chat, the plugin dosnt work

Here is my sp file and i use this site https://spider.limetech.io/

[z4lab-hub.zip](https://github.com/z4lab/z4lab-hub/files/4129791/z4lab-hub.zip)

**Comment by 13ace37** [comment]
![image](https://user-images.githubusercontent.com/29045525/73384505-adce6380-42cb-11ea-8518-9fb9a8401ee3.png)
Check before you open an issue next time pls.

**Comment by Quaticy** [comment]
What do you mean? i drag the file in and compile it

**Comment by 13ace37** [comment]
1. you fucked up the whole plugin
2. stop using a stupid web based compiler
3. check your files w/ `git diff`

**Comment by Quaticy** [comment]
Im all new to this, but this is what you told me:


normally you would use the binary compiler. but for single filed plugins, you can use https://www.sourcemod.net/compiler.php
--

**Comment by Quaticy** [comment]
And i get this error when trying to use that site


SourcePawn Compiler 1.10.0.6453
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

/home/groups/sourcemod/upload_tmp/phppPdfSo.sp(2) : fatal error 183: cannot read from file: "colorvariables"

Compilation aborted.
1 Error.

791373 successful compiles to date.
634201 failed compiles to date.

**Comment by 13ace37** [comment]
Im not google btw. But how about [this](https://forums.alliedmods.net/showthread.php?t=267743)?

**Comment by Quaticy** [comment]
Im a newbie to this, am i suppose to make a file or smth?

**Comment by 13ace37** [comment]
1. git clone this repo
2. make your changes to the sp file
3. create a folder named `includes` in the `./scripting` folder
4. ```wget https://github.com/PremyslTalich/ColorVariables/blob/master/addons/sourcemod/scripting/includes/colorvariables.inc``` into there
5. compile the sp file using the [binary files](https://www.sourcemod.net/downloads.php?branch=stable)
6. move the plugin into your plugins folder
